name: Action A 

on:
  workflow_call:
    inputs:
      name:
        description: 'Enter your name'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter your name'
        required: true

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Action B
        id: action-b
        uses: ./.github/workflows/ActionB.yml
        with:
          name: ${{inputs.name}}

  say_goodbye:
    needs: say_hello
    runs-on: ubuntu-latest
    steps:
      - name: Say Goodbye
        run: echo "Goodbye, ${{inputs.name}}"
