name: Action A 

on:
  workflow_call:
    inputs:
      name:
        description: 'Enter your name'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter your name'
        required: true
jobs:
  say_hello:
        uses: ./.github/workflows/ActionB.yml
        with:
          name: ${{inputs.name}}
        secrets: inherit

        
  say_goodbye:
    needs: say_hello
    runs-on: ubuntu-latest
    steps:
      - name: Say Goodbye
        run: echo "Goodbye, ${{inputs.name}}"
