name: Action C

on:
  workflow_call:
    inputs:
      name:
        description: 'Enter your name'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter your name'
        required: true

jobs:
  hi:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hi
        run: echo "Hi, ${{inputs.name}}"

  say_hello:
    needs: hi
    runs-on: ubuntu-latest
    steps:
      - name: Run Action B
        uses: ./.github/workflows/ActionB.yml
        with:
          name: ${{inputs.name}}

  say_goodbye:
    needs: say_hello
    runs-on: ubuntu-latest
    steps:
      - name: Say Goodbye
        run: echo "Goodbye, ${{inputs.name}}"
