name: Check SSH
on:
  push:
    branches:
      - main

jobs:
  push-to-azure-container-registry:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
       host: ${{ secrets.AZURE_VM_IP }}
       username: ${{ secrets.AZURE_VM_USER}}
       key: ${{ secrets.SSH_PRIVATE_KEY}}
       port: 222
       script: whoami
